<?php

include "_bottom.php";
?>
</div>
<script src="js/jquery.min.js"></script>
<script src="js/era.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>

<!--  script for the timelines  -->
<script src="https://cdn.knightlab.com/libs/timeline3/latest/js/timeline.js"></script> 
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<!--  script for country select -->
<script src="js/bootstrap-select-country.min.js"></script>
<?php  testvar();?>