</div>

<script src="js/jquery.min.js"></script>
<script src="js/era.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<script src="https://unpkg.com/vue@^2/dist/vue.min.js"></script>
<script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.0.0/webcomponents-loader.js"></script>
<script src="https://unpkg.com/data-metrics-badge/dist/data-metrics-badge.min.js"></script>
<!--  script for the timelines  -->
<script src="https://cdn.knightlab.com/libs/timeline3/latest/js/timeline.js"></script>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<!--  script for country select -->
<script src="js/bootstrap-select-country.min.js"></script>